#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Rick" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3JxaWlpL2JvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO == "Rick" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3JxaWlpL2JvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3JxaWlpL2JvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi 
}


_setting_bot () {
    local zippath
    zippath="RickBot.zip"
    echo "- يتم تحميل ملفات سورس ديو ⏳"
    wget -q $(_get_repolink) -O "$zippath"
    echo "- فك بيانات سورس ديو ⚙️"
    rickpath=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "- تم فك وتحميل الملفات وبيانات سورس ديو 🔨"
    echo "- يتم التفريغ ⛓"
    rm -rf "$zippath"
    sleep 5
    cd $rickpath
    echo "- يتم البدء في تحميل سورس ديو ⌛️"
    echo "
    
      ___                       ___           ___     
     /  /\        ___          /  /\         /__/|    
    /  /::\      /  /\        /  /:/        |  |:|    
   /  /:/\:\    /  /:/       /  /:/         |  |:|    
  /  /:/~/:/   /__/::\      /  /:/  ___   __|  |:|    
 /__/:/ /:/___ \__\/\:\__  /__/:/  /  /\ /__/\_|:|____
 \  \:\/:::::/    \  \:\/\ \  \:\ /  /:/ \  \:\/:::::/
  \  \::/~~~~      \__\::/  \  \:\  /:/   \  \::/~~~~ 
   \  \:\          /__/:/    \  \:\/:/     \  \:\     
    \  \:\         \__\/      \  \::/       \  \:\    
     \__\/                     \__\/         \__\/    

"

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot
